#!/usr/bin/env bash
#Installing nginx using it in port 80
sudo apt-get -y update
sudo apt-get install -y nginx

sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'

sudo service nginx start
