#!/usr/bin/env bash
#Configure our HAProxy so that it tracks the two servers using roundrobin algo
text="frontend myfrontend
	bind *:80
	default_backend mybackend
backend mybackend
	balance roundrobin
	server server1 100.25.164.203:80 check
	server server2 54.90.3.135:80 check"
echo "$text" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
sudo service haproxy restart
