#!/usr/bin/env bash
#This will configure my nginx web server
sed -i 's/[0-9]\+ default_server/80 default_server/' /etc/nginx/sites-enabled/default
service nginx restart
sed -i "s/.*status_of_proc -p.*/\t\techo \" \* nginx is not running\"/g" /etc/init.d/nginx
