#!/usr/bin/env bash
#This is our file

func() {
	rm "/var/run/myscript.pid"
	kill -15 $$
}

trap "echo I hate the kill command" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap func SIGQUIT
trap func SIGTERM

touch "/var/run/myscript.pid"
pid=$(pgrep -f "/var/run/myscript.pid")
echo "$pid" > "/var/run/myscript.pid"
while (true); do
	echo "To infinity and beyond"
done
