#!/usr/bin/env bash
#This is 101.task
file="/etc/passwd"
while IFS= read -r line; do
	USERNAME=$(cut -d ":" -f 1 <<< "$line")
	PASSWORD=$(cut -d ":" -f 2 <<< "$line")
	USER_ID=$(cut -d ":" -f 3 <<< "$line")
	GROUP_ID=$(cut -d ":" -f 4 <<< "$line")
	USER_ID_INFO=$(cut -d ":" -f 5 <<< "$line")
	HOME_DIRECTORY=$(cut -d ":" -f 6 <<< "$line")
	COMMAND_SHELL=$(cut -d ":" -f 7 <<< "$line")
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < "$file"
