#!/usr/bin/env bash
#list current directory beginning with first dash
list="$(ls .)"
for i in "$list"; do
	a=0
	for j in "$i"; do
		if [ $a -ne 0 ]
		then
			printf "$j"
		fi
		if [ "$j" -eq "-" ]
		then
			((a++))
		fi
	done
done
