#!/usr/bin/env bash
#list current directory beginning with first dash
mapfile -t list < <(ls -- *)
a=0
for i in "${list[@]}"; do
	for ((j = 0; j < ${#i}; j++)); do
		char="${i:j:1}"
		if [ $a -ne 0 ]; then
			printf '%s' "$char"
		fi
		if [ "$char" = "-" ]; then
			a=1
		fi
	done
	if [ $a -ne 0 ]; then
		printf "\n"
	fi
	a=0
done
